### ISSUE TITLE
WireHub Sandbox not in Docker Hub.

### ISSUE THREAD

**Issue by bigeasy** [Gawen/WireHub#1]
```
 % docker pull wirehub/sandbox
Using default tag: latest
Error response from daemon: manifest for wirehub/sandbox:latest not found
```

**Comment by bigeasy** [comment]
Didn't read the `README.md` carefully. Now I wish I could delete this.

**Comment by bigeasy** [comment]
Got `wh` running in Docker on Ubuntu in VirtualBox on OS X. Build and configured and interfaces are present but unable to ping the peer. WireGuard kernel module loaded. Currently on a hotel network, so maybe there's an aggressive firewall somewhere working against me.

Am I correct in assuming that the `tWTOaY8X5XXtC4VzN0EEr_H3dTG0Hos5hCJ7mqxk_Fw` value in the documentation is not actually supposed used? Would it look more like the user experience to replace that value with `zW-1lBeQ7IkT6NW6hL_NsV4eOPOwJi_rt1vO-omOEmQ` in the key generation example code?

**Comment by bigeasy** [comment]
It works. Had to configure NAT in `iptables` on the Ubuntu host running Docker.

**Comment by Gawen** [comment]
Hello @bigeasy. Thanks for reporting the first issue :tada: 

> ```
>  % docker pull wirehub/sandbox
> Using default tag: latest
> Error response from daemon: manifest for wirehub/sandbox:latest not found
> ```

You're probably not the only one. I will push the images in docker's hub when it will be stable enough.

> It works. Had to configure NAT in `iptables` on the Ubuntu host running Docker.

Interesting. Was the container able to contact Internet before configuring `iptables` ?

NOTE: closed by mistake

**Comment by Gawen** [comment]
`wirehub/wh` and `wirehub/sandbox` are pushed in the Docker Images Hub.
